name: 🧪

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log a debug message
        run: >-
          echo "::debug::IN DEBUG MODE"
      - name: Log debug context
        run: |
          echo 'RUNNER_DEBUG='"${RUNNER_DEBUG}"
          echo 'runner.debug=${{ runner.debug }}'
          echo 'ACTIONS_RUNNER_DEBUG='"${ACTIONS_RUNNER_DEBUG}"
          echo 'secrets.ACTIONS_RUNNER_DEBUG=${{
            secrets.ACTIONS_RUNNER_DEBUG == 'true'
            && 'true'
            || 'false'
          }}'
          echo 'vars.ACTIONS_RUNNER_DEBUG=${{ vars.ACTIONS_RUNNER_DEBUG }}'

          echo 'ACTIONS_STEP_DEBUG='"${ACTIONS_STEP_DEBUG}"
          echo 'secrets.ACTIONS_STEP_DEBUG=${{
            secrets.ACTIONS_STEP_DEBUG == 'true'
            && 'true'
            || 'false'
          }}'
          echo 'vars.ACTIONS_STEP_DEBUG=${{ vars.ACTIONS_STEP_DEBUG }}'
